server:
  port: 8006
spring:
  application:
    name: gmallpassport
  redis:
    host: localhost
    port: 6379
    database: 2
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  activemq:
    broker-url: tcp://192.168.6.128:61616
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/