server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gmall?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    password: daitian123
    username: root
  application:
    name: gmalluser
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
