server:
  port: 8010
spring:
  application:
    name: gmallseckill
  redis:
    host: localhost
    port: 6379
    database: 1
  activemq:
    broker-url: tcp://192.168.6.128:61616
  datasource:
    url: jdbc:mysql://localhost:3306/gmall?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    password: daitian123
    username: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
