server:
  port: 8002
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gmall?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    password: daitian123
    username: root
  application:
    name: gmallmanager
  redis:
    host: localhost
    port: 6379
    database: 2
  elasticsearch:
    jest:
      uris: http://192.168.6.128:9200
  activemq:
    broker-url: tcp://192.168.6.128:61616
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true